[package]
name = "jsonic"
version = "0.1.7"
edition = "2021"
description = "Fast, small JSON parsing library for rust with no dependencies"
license = "MIT OR Apache-2.0"
repository = "https://github.com/k0dai/jsonic"

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = "fat"
debug-assertions = false
codegen-units = 1
panic = "unwind"
incremental = false
overflow-checks = false